name: GitHub Actions Demo
on:
  pull_request:
      branches:
        - Atividade-Formativa-2
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pyLint