name: Discord

on:
  - push

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify Discord
        uses: johnnyhuy/actions-discord-git-webhook@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}

