name: Discord

on:
  pull_request:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Notify Discord
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
